version: "3.8"

services:
  chatbot-database:
    ports:
      - "6003:6003"
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - REDIS_HOST=10.0.1.4
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_DECODE_RESPONSES=True
    restart: always
