version: "3.8"

services:
  chatbot-database:
    ports:
      - "6003:6003"
    environment:
      - FLASK_ENV=deployment
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=${REDIS_DB}
      - REDIS_DECODE_RESPONSES=${REDIS_DECODE_RESPONSES}
    restart: always
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    container_name: redis-container
    ports:
      - "6379:6379"
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  redis_data:
