version: "3.8"

services:
  chatbot-database:
    ports:
      - "6003:6003"
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_DECODE_RESPONSES=${REDIS_DECODE_RESPONSES}
    restart: always
