version: "3.8"

services:
  chatbot-database:
    ports:
      - "6003:6003"
    environment:
      - FLASK_ENV=deployment
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    restart: always
